# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from shared.proto import common_pb2 as shared_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='security.proto',
  package='ha.security',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0esecurity.proto\x12\x0bha.security\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19shared/proto/common.proto\"0\n\x06\x43onfig\x12&\n\x10security_service\x18\x01 \x01(\x0b\x32\x0c.ha.Endpoint\"C\n\x12StreamVideoRequest\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x15\n\x13StreamVideoResponse2i\n\x0fSecurityService\x12V\n\x0bStreamVideo\x12\x1f.ha.security.StreamVideoRequest\x1a .ha.security.StreamVideoResponse\"\x00(\x01\x30\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,shared_dot_proto_dot_common__pb2.DESCRIPTOR,])




_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='ha.security.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='security_service', full_name='ha.security.Config.security_service', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=200,
)


_STREAMVIDEOREQUEST = _descriptor.Descriptor(
  name='StreamVideoRequest',
  full_name='ha.security.StreamVideoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ha.security.StreamVideoRequest.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=269,
)


_STREAMVIDEORESPONSE = _descriptor.Descriptor(
  name='StreamVideoResponse',
  full_name='ha.security.StreamVideoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=292,
)

_CONFIG.fields_by_name['security_service'].message_type = shared_dot_proto_dot_common__pb2._ENDPOINT
_STREAMVIDEOREQUEST.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['StreamVideoRequest'] = _STREAMVIDEOREQUEST
DESCRIPTOR.message_types_by_name['StreamVideoResponse'] = _STREAMVIDEORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.Config)
  })
_sym_db.RegisterMessage(Config)

StreamVideoRequest = _reflection.GeneratedProtocolMessageType('StreamVideoRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMVIDEOREQUEST,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.StreamVideoRequest)
  })
_sym_db.RegisterMessage(StreamVideoRequest)

StreamVideoResponse = _reflection.GeneratedProtocolMessageType('StreamVideoResponse', (_message.Message,), {
  'DESCRIPTOR' : _STREAMVIDEORESPONSE,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.StreamVideoResponse)
  })
_sym_db.RegisterMessage(StreamVideoResponse)



_SECURITYSERVICE = _descriptor.ServiceDescriptor(
  name='SecurityService',
  full_name='ha.security.SecurityService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=294,
  serialized_end=399,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamVideo',
    full_name='ha.security.SecurityService.StreamVideo',
    index=0,
    containing_service=None,
    input_type=_STREAMVIDEOREQUEST,
    output_type=_STREAMVIDEORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SECURITYSERVICE)

DESCRIPTOR.services_by_name['SecurityService'] = _SECURITYSERVICE

# @@protoc_insertion_point(module_scope)
