# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from shared.proto import common_pb2 as shared_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='security.proto',
  package='ha.security',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0esecurity.proto\x12\x0bha.security\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19shared/proto/common.proto\"?\n\x07\x41rchive\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x10\n\x08max_size\x18\x02 \x01(\x03\x12\x10\n\x08max_days\x18\x03 \x01(\x05\"w\n\x05Video\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x11\n\tframerate\x18\x03 \x01(\x05\x12\x0f\n\x07quality\x18\x04 \x01(\x05\x12+\n\rlocal_archive\x18\x05 \x01(\x0b\x32\x14.ha.security.Archive\"8\n\tComponent\x12#\n\x05video\x18\x01 \x01(\x0b\x32\x12.ha.security.VideoH\x00\x42\x06\n\x04kind\"L\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12*\n\ncomponents\x18\x03 \x03(\x0b\x32\x16.ha.security.Component\"\xaf\x01\n\x06\x43onfig\x12&\n\x10security_service\x18\x01 \x01(\x0b\x32\x0c.ha.Endpoint\x12\x1b\n\x05kafka\x18\x02 \x01(\x0b\x32\x0c.ha.Endpoint\x12\x1d\n\x07mongodb\x18\x03 \x01(\x0b\x32\x0c.ha.Endpoint\x12\x1f\n\twebserver\x18\x04 \x01(\x0b\x32\x0c.ha.Endpoint\x12 \n\x05nodes\x18\x05 \x03(\x0b\x32\x11.ha.security.Node\"&\n\x13RegisterNodeRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"7\n\x14RegisterNodeResponse\x12\x1f\n\x04node\x18\x01 \x01(\x0b\x32\x11.ha.security.Node\"c\n\x12StreamVideoRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05image\x18\x03 \x01(\x0c\"\x15\n\x13StreamVideoResponse2\xc0\x01\n\x0fSecurityService\x12U\n\x0cRegisterNode\x12 .ha.security.RegisterNodeRequest\x1a!.ha.security.RegisterNodeResponse\"\x00\x12V\n\x0bStreamVideo\x12\x1f.ha.security.StreamVideoRequest\x1a .ha.security.StreamVideoResponse\"\x00(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,shared_dot_proto_dot_common__pb2.DESCRIPTOR,])




_ARCHIVE = _descriptor.Descriptor(
  name='Archive',
  full_name='ha.security.Archive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='ha.security.Archive.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_size', full_name='ha.security.Archive.max_size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_days', full_name='ha.security.Archive.max_days', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=215,
)


_VIDEO = _descriptor.Descriptor(
  name='Video',
  full_name='ha.security.Video',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ha.security.Video.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ha.security.Video.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='framerate', full_name='ha.security.Video.framerate', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quality', full_name='ha.security.Video.quality', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_archive', full_name='ha.security.Video.local_archive', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=336,
)


_COMPONENT = _descriptor.Descriptor(
  name='Component',
  full_name='ha.security.Component',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video', full_name='ha.security.Component.video', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='ha.security.Component.kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=338,
  serialized_end=394,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='ha.security.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ha.security.Node.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ha.security.Node.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='components', full_name='ha.security.Node.components', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=472,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='ha.security.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='security_service', full_name='ha.security.Config.security_service', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kafka', full_name='ha.security.Config.kafka', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mongodb', full_name='ha.security.Config.mongodb', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='webserver', full_name='ha.security.Config.webserver', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='ha.security.Config.nodes', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=650,
)


_REGISTERNODEREQUEST = _descriptor.Descriptor(
  name='RegisterNodeRequest',
  full_name='ha.security.RegisterNodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='ha.security.RegisterNodeRequest.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=690,
)


_REGISTERNODERESPONSE = _descriptor.Descriptor(
  name='RegisterNodeResponse',
  full_name='ha.security.RegisterNodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='ha.security.RegisterNodeResponse.node', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=692,
  serialized_end=747,
)


_STREAMVIDEOREQUEST = _descriptor.Descriptor(
  name='StreamVideoRequest',
  full_name='ha.security.StreamVideoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='ha.security.StreamVideoRequest.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ha.security.StreamVideoRequest.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='ha.security.StreamVideoRequest.image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=749,
  serialized_end=848,
)


_STREAMVIDEORESPONSE = _descriptor.Descriptor(
  name='StreamVideoResponse',
  full_name='ha.security.StreamVideoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=850,
  serialized_end=871,
)

_VIDEO.fields_by_name['local_archive'].message_type = _ARCHIVE
_COMPONENT.fields_by_name['video'].message_type = _VIDEO
_COMPONENT.oneofs_by_name['kind'].fields.append(
  _COMPONENT.fields_by_name['video'])
_COMPONENT.fields_by_name['video'].containing_oneof = _COMPONENT.oneofs_by_name['kind']
_NODE.fields_by_name['components'].message_type = _COMPONENT
_CONFIG.fields_by_name['security_service'].message_type = shared_dot_proto_dot_common__pb2._ENDPOINT
_CONFIG.fields_by_name['kafka'].message_type = shared_dot_proto_dot_common__pb2._ENDPOINT
_CONFIG.fields_by_name['mongodb'].message_type = shared_dot_proto_dot_common__pb2._ENDPOINT
_CONFIG.fields_by_name['webserver'].message_type = shared_dot_proto_dot_common__pb2._ENDPOINT
_CONFIG.fields_by_name['nodes'].message_type = _NODE
_REGISTERNODERESPONSE.fields_by_name['node'].message_type = _NODE
_STREAMVIDEOREQUEST.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Archive'] = _ARCHIVE
DESCRIPTOR.message_types_by_name['Video'] = _VIDEO
DESCRIPTOR.message_types_by_name['Component'] = _COMPONENT
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['RegisterNodeRequest'] = _REGISTERNODEREQUEST
DESCRIPTOR.message_types_by_name['RegisterNodeResponse'] = _REGISTERNODERESPONSE
DESCRIPTOR.message_types_by_name['StreamVideoRequest'] = _STREAMVIDEOREQUEST
DESCRIPTOR.message_types_by_name['StreamVideoResponse'] = _STREAMVIDEORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Archive = _reflection.GeneratedProtocolMessageType('Archive', (_message.Message,), {
  'DESCRIPTOR' : _ARCHIVE,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.Archive)
  })
_sym_db.RegisterMessage(Archive)

Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), {
  'DESCRIPTOR' : _VIDEO,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.Video)
  })
_sym_db.RegisterMessage(Video)

Component = _reflection.GeneratedProtocolMessageType('Component', (_message.Message,), {
  'DESCRIPTOR' : _COMPONENT,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.Component)
  })
_sym_db.RegisterMessage(Component)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.Node)
  })
_sym_db.RegisterMessage(Node)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.Config)
  })
_sym_db.RegisterMessage(Config)

RegisterNodeRequest = _reflection.GeneratedProtocolMessageType('RegisterNodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERNODEREQUEST,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.RegisterNodeRequest)
  })
_sym_db.RegisterMessage(RegisterNodeRequest)

RegisterNodeResponse = _reflection.GeneratedProtocolMessageType('RegisterNodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERNODERESPONSE,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.RegisterNodeResponse)
  })
_sym_db.RegisterMessage(RegisterNodeResponse)

StreamVideoRequest = _reflection.GeneratedProtocolMessageType('StreamVideoRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMVIDEOREQUEST,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.StreamVideoRequest)
  })
_sym_db.RegisterMessage(StreamVideoRequest)

StreamVideoResponse = _reflection.GeneratedProtocolMessageType('StreamVideoResponse', (_message.Message,), {
  'DESCRIPTOR' : _STREAMVIDEORESPONSE,
  '__module__' : 'security_pb2'
  # @@protoc_insertion_point(class_scope:ha.security.StreamVideoResponse)
  })
_sym_db.RegisterMessage(StreamVideoResponse)



_SECURITYSERVICE = _descriptor.ServiceDescriptor(
  name='SecurityService',
  full_name='ha.security.SecurityService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=874,
  serialized_end=1066,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterNode',
    full_name='ha.security.SecurityService.RegisterNode',
    index=0,
    containing_service=None,
    input_type=_REGISTERNODEREQUEST,
    output_type=_REGISTERNODERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamVideo',
    full_name='ha.security.SecurityService.StreamVideo',
    index=1,
    containing_service=None,
    input_type=_STREAMVIDEOREQUEST,
    output_type=_STREAMVIDEORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SECURITYSERVICE)

DESCRIPTOR.services_by_name['SecurityService'] = _SECURITYSERVICE

# @@protoc_insertion_point(module_scope)
