# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import security_pb2 as security__pb2


class SecurityServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterNode = channel.unary_unary(
        '/ha.security.SecurityService/RegisterNode',
        request_serializer=security__pb2.RegisterNodeRequest.SerializeToString,
        response_deserializer=security__pb2.RegisterNodeResponse.FromString,
        )
    self.StreamVideo = channel.stream_stream(
        '/ha.security.SecurityService/StreamVideo',
        request_serializer=security__pb2.StreamVideoRequest.SerializeToString,
        response_deserializer=security__pb2.StreamVideoResponse.FromString,
        )


class SecurityServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RegisterNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamVideo(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SecurityServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterNode': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterNode,
          request_deserializer=security__pb2.RegisterNodeRequest.FromString,
          response_serializer=security__pb2.RegisterNodeResponse.SerializeToString,
      ),
      'StreamVideo': grpc.stream_stream_rpc_method_handler(
          servicer.StreamVideo,
          request_deserializer=security__pb2.StreamVideoRequest.FromString,
          response_serializer=security__pb2.StreamVideoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ha.security.SecurityService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
