# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import irrigation_pb2 as irrigation__pb2


class IrrigationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetConfig = channel.unary_unary(
        '/IrrigationService/GetConfig',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=irrigation__pb2.Config.FromString,
        )
    self.SubmitTasks = channel.unary_unary(
        '/IrrigationService/SubmitTasks',
        request_serializer=irrigation__pb2.TaskList.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetCurrentTask = channel.unary_unary(
        '/IrrigationService/GetCurrentTask',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=irrigation__pb2.Task.FromString,
        )
    self.GetPendingTasks = channel.unary_unary(
        '/IrrigationService/GetPendingTasks',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=irrigation__pb2.TaskList.FromString,
        )


class IrrigationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitTasks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCurrentTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPendingTasks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IrrigationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetConfig': grpc.unary_unary_rpc_method_handler(
          servicer.GetConfig,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=irrigation__pb2.Config.SerializeToString,
      ),
      'SubmitTasks': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitTasks,
          request_deserializer=irrigation__pb2.TaskList.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetCurrentTask': grpc.unary_unary_rpc_method_handler(
          servicer.GetCurrentTask,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=irrigation__pb2.Task.SerializeToString,
      ),
      'GetPendingTasks': grpc.unary_unary_rpc_method_handler(
          servicer.GetPendingTasks,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=irrigation__pb2.TaskList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'IrrigationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
