# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from shared.proto import common_pb2 as shared_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='weather.proto',
  package='ha.weather',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rweather.proto\x12\nha.weather\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19shared/proto/common.proto\"e\n\x06\x43onfig\x12 \n\x18open_weather_map_api_key\x18\x01 \x01(\t\x12\x1b\n\x05kafka\x18\x02 \x01(\x0b\x32\x0c.ha.Endpoint\x12\x1c\n\x14weather_service_port\x18\x03 \x01(\x05\"\x86\x02\n\x08Snapshot\x12\x0f\n\x07zipcode\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rtemperature_c\x18\x03 \x01(\x02\x12\x13\n\x0bpressure_pa\x18\x04 \x01(\x02\x12\x10\n\x08humidity\x18\x05 \x01(\x02\x12\x14\n\x0cvisibility_m\x18\x06 \x01(\x02\x12\x16\n\x0ewind_speed_mps\x18\x07 \x01(\x02\x12\x16\n\x0ewind_direction\x18\x08 \x01(\x02\x12\"\n\x1alast_1_hour_rain_amount_mm\x18\t \x01(\x02\x12\x12\n\ncloudiness\x18\n \x01(\x02\"8\n\x13GetSnapshotsRequest\x12\x0f\n\x07zipcode\x18\x01 \x01(\t\x12\x10\n\x08max_days\x18\x02 \x01(\x05\"?\n\x14GetSnapshotsResponse\x12\'\n\tsnapshots\x18\x01 \x03(\x0b\x32\x14.ha.weather.Snapshot2e\n\x0eWeatherService\x12S\n\x0cGetSnapshots\x12\x1f.ha.weather.GetSnapshotsRequest\x1a .ha.weather.GetSnapshotsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,shared_dot_proto_dot_common__pb2.DESCRIPTOR,])




_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='ha.weather.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='open_weather_map_api_key', full_name='ha.weather.Config.open_weather_map_api_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kafka', full_name='ha.weather.Config.kafka', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weather_service_port', full_name='ha.weather.Config.weather_service_port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=190,
)


_SNAPSHOT = _descriptor.Descriptor(
  name='Snapshot',
  full_name='ha.weather.Snapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zipcode', full_name='ha.weather.Snapshot.zipcode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ha.weather.Snapshot.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature_c', full_name='ha.weather.Snapshot.temperature_c', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pressure_pa', full_name='ha.weather.Snapshot.pressure_pa', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='ha.weather.Snapshot.humidity', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visibility_m', full_name='ha.weather.Snapshot.visibility_m', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wind_speed_mps', full_name='ha.weather.Snapshot.wind_speed_mps', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wind_direction', full_name='ha.weather.Snapshot.wind_direction', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_1_hour_rain_amount_mm', full_name='ha.weather.Snapshot.last_1_hour_rain_amount_mm', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cloudiness', full_name='ha.weather.Snapshot.cloudiness', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=455,
)


_GETSNAPSHOTSREQUEST = _descriptor.Descriptor(
  name='GetSnapshotsRequest',
  full_name='ha.weather.GetSnapshotsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zipcode', full_name='ha.weather.GetSnapshotsRequest.zipcode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_days', full_name='ha.weather.GetSnapshotsRequest.max_days', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=513,
)


_GETSNAPSHOTSRESPONSE = _descriptor.Descriptor(
  name='GetSnapshotsResponse',
  full_name='ha.weather.GetSnapshotsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshots', full_name='ha.weather.GetSnapshotsResponse.snapshots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=578,
)

_CONFIG.fields_by_name['kafka'].message_type = shared_dot_proto_dot_common__pb2._ENDPOINT
_SNAPSHOT.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETSNAPSHOTSRESPONSE.fields_by_name['snapshots'].message_type = _SNAPSHOT
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['Snapshot'] = _SNAPSHOT
DESCRIPTOR.message_types_by_name['GetSnapshotsRequest'] = _GETSNAPSHOTSREQUEST
DESCRIPTOR.message_types_by_name['GetSnapshotsResponse'] = _GETSNAPSHOTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:ha.weather.Config)
  })
_sym_db.RegisterMessage(Config)

Snapshot = _reflection.GeneratedProtocolMessageType('Snapshot', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOT,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:ha.weather.Snapshot)
  })
_sym_db.RegisterMessage(Snapshot)

GetSnapshotsRequest = _reflection.GeneratedProtocolMessageType('GetSnapshotsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSNAPSHOTSREQUEST,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:ha.weather.GetSnapshotsRequest)
  })
_sym_db.RegisterMessage(GetSnapshotsRequest)

GetSnapshotsResponse = _reflection.GeneratedProtocolMessageType('GetSnapshotsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSNAPSHOTSRESPONSE,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:ha.weather.GetSnapshotsResponse)
  })
_sym_db.RegisterMessage(GetSnapshotsResponse)



_WEATHERSERVICE = _descriptor.ServiceDescriptor(
  name='WeatherService',
  full_name='ha.weather.WeatherService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=580,
  serialized_end=681,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSnapshots',
    full_name='ha.weather.WeatherService.GetSnapshots',
    index=0,
    containing_service=None,
    input_type=_GETSNAPSHOTSREQUEST,
    output_type=_GETSNAPSHOTSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEATHERSERVICE)

DESCRIPTOR.services_by_name['WeatherService'] = _WEATHERSERVICE

# @@protoc_insertion_point(module_scope)
